Add custom format support
prettytable/prettytable pull request #136
Opened 2021-10-08 01:03 UTC by davzucky

* Fixes https://github.com/jazzband/prettytable/issues/105.
* Fixes https://github.com/jazzband/prettytable/issues/92.
* Fixes https://github.com/jazzband/prettytable/issues/99.

This change should be able to address all the following issues.
It add the capability to set custom formatter for any column as callable. You can set as well
``` python
        pt = PrettyTable(["col_date", "col_str", "col_float", "col_int"])
        pt.add_row([date(2021, 1, 1), "January", 12345.12345, 12345678])
        pt.add_row([date(2021, 2, 1), "February", 54321.12345, 87654321])
        pt.custom_format["col_date"] = lambda f, v: v.strftime("%d %b %Y")
        pt.custom_format["col_float"] = lambda f, v: f"{v:.3f}"
        pt.custom_format["col_int"] = lambda f, v: f"{v:,}"
```

would generate a table like that

```
+-------------+----------+-----------+------------+
|   col_date  | col_str  | col_float |  col_int   |
+-------------+----------+-----------+------------+
| 01 Jan 2021 | January  | 12345.123 | 12,345,678 |
| 01 Feb 2021 | February | 54321.123 | 87,654,321 |
+-------------+----------+-----------+------------+
```
This PR should help with all below issues:
- https://github.com/jazzband/prettytable/issues/105
- https://github.com/jazzband/prettytable/issues/92
- https://github.com/jazzband/prettytable/issues/99

2021-10-08 10:40 UTC, hugovk requested changes
Please also check the failing lint check. You can autofix some of them like:

```
python -m pip install -U pre-commit && pre-commit run --all-files
```

(And optionally `pre-commit install` to check your future commits.)

2021-10-08 10:40 UTC, hugovk commented on README.md
> +: `pf.custom_format["my_col_int"] = ()lambda f, v: f"{v:,}"`. The type of the callable if
```suggestion
- `custom_format` - A Dictionary of field and callable. This allow you to set any format you want:
`pf.custom_format["my_col_int"] = ()lambda f, v: f"{v:,}"`. The type of the callable if 
```

2021-10-08 10:40 UTC, hugovk commented on tests/test_prettytable.py
> +from datetime import date
Let's import like this:
```suggestion
import datetime as dt
```
And then use `dt.date` below.

See: https://adamj.eu/tech/2019/09/12/how-i-import-pythons-datetime-module/

2021-10-08 10:40 UTC, hugovk commented on tests/test_prettytable.py
> +        pt.add_row([date(2021, 2, 1), "February", 54321.12345, 87654321])
```suggestion
        pt.add_row([dt.date(2021, 1, 1), "January", 12345.12345, 12345678])
        pt.add_row([dt.date(2021, 2, 1), "February", 54321.12345, 87654321])
```

2021-10-08 10:40 UTC, hugovk commented on tests/test_prettytable.py
> +        pt.add_row([date(2021, 2, 1), "February", 54321.12345, 87654321])
```suggestion
        pt.add_row([dt.date(2021, 1, 1), "January", 12345.12345, 12345678])
        pt.add_row([dt.date(2021, 2, 1), "February", 54321.12345, 87654321])
```

2021-10-08 12:04 UTC, davzucky commented on README.md
> +: `pf.custom_format["my_col_int"] = ()lambda f, v: f"{v:,}"`. The type of the callable if
Fixed

2021-10-08 12:04 UTC, davzucky commented on tests/test_prettytable.py
> +from datetime import date
Fixed

2021-10-08 12:05 UTC, davzucky commented on tests/test_prettytable.py
> +        pt.add_row([date(2021, 2, 1), "February", 54321.12345, 87654321])
Fixed

2021-10-08 12:05 UTC, davzucky commented on tests/test_prettytable.py
> +        pt.add_row([date(2021, 2, 1), "February", 54321.12345, 87654321])
Fixed

2021-10-08 12:05 UTC, davzucky commented
Sorry I ran the pre-commit but forgot on the last changes :-(. 
Everything should be fine now

2021-10-20 12:01 UTC, davzucky commented
@hugovk Are you missing anything to get this change merge ?

2021-10-20 12:15 UTC, hugovk commented
I wanted to give a bit of time to get some feedback from the participants of https://github.com/jazzband/prettytable/issues/105 https://github.com/jazzband/prettytable/issues/92 https://github.com/jazzband/prettytable/issues/99.

So far one person responded positively, so that's 100%! Let's get this merged, thanks!

2021-10-20 12:17 UTC, hugovk approved these changes

2021-10-20 12:18 UTC, merged