Add Jupyter repr and default interpreter repr methods
prettytable/prettytable pull request #146
Opened 2021-10-28 10:36 UTC by amirali

Fixes #127.

I added the features they talked about them in #127.

2021-10-28 11:05 UTC, hugovk requested changes
Thank you! Please could you add tests to cover these lines?

2021-10-28 11:28 UTC, amirali commented
I added the test for new repr and Jupyter environment repr. Sorry I didn't add them at first

2021-10-28 11:57 UTC, kumaraditya303 submitted a review, later dismissed

2021-10-28 11:57 UTC, kumaraditya303 commented on tests/test_prettytable.py
> +class TestRepr:
A test for `__getattr__` with `_repr_html_` is required, Thank you

2021-10-28 21:51 UTC, amirali commented on tests/test_prettytable.py
> +class TestRepr:
Written here 921bdbe

2021-10-29 05:01 UTC, flutefreak7 commented
This looks good to me! I'm the author of #127

2021-10-29 09:06 UTC, hugovk commented on tests/test_prettytable.py
> +def simple_table():
Can we reuse an existing fixture instead of creating a new one?

2021-10-29 13:11 UTC, hugovk commented
I'm not sure if my earlier review comments saved properly, will try again!

---

Do we need this as an attribute?

```python
        elif name == "_repr_html_":
            return self._repr_html_()
```

Looks like IPython only needs the method, not attribute:

* https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

2021-10-29 13:19 UTC, amirali commented
When I implemented the method, in the first runs in Jupyter it doesn't show the expected value in HTML and got AttriubuteError on calling the method. So I thought it should be registered as an attribute. But if you think it's not necessary I'll double-check it and remove the extra part.

2021-10-29 13:49 UTC, hugovk commented
I'm not super familiar with IPython / JupyterLab but seemed to work fine for me without the attribute:

![image](https://user-images.githubusercontent.com/1324225/139446598-85f0a591-8c6c-47b7-a96d-5934ce4d362e.png)

Let's remove it, and if it's needed later it's easy to add. Thanks!

2021-10-29 14:45 UTC, amirali commented
Done.

2021-10-29 16:04 UTC, hugovk approved these changes

2021-10-29 16:05 UTC, merged

2021-10-29 16:05 UTC, hugovk commented
Thank you!