Added flag to allow preservation of internal borders when border=False
prettytable/prettytable pull request #180
Opened 2022-04-26 12:53 UTC by myheroyuki

Addresses issue #178

2022-04-26 15:48 UTC, hugovk requested changes
Thanks for the PR!

2022-04-26 15:48 UTC, hugovk commented on tests/test_prettytable.py
> +""".strip()
```suggestion
""".strip()  # noqa: E501
```

2022-04-26 15:48 UTC, hugovk commented on tests/test_prettytable.py
> +""".strip()
```suggestion
 value 7 |  value8 |  value9  
""".strip(). # noqa: W291
```

2022-04-26 15:48 UTC, hugovk commented on src/prettytable/prettytable.py
> +            self._preserve_internal_border = kwargs["preserve_internal_border"]
Is this line needed? If so, please can you add tests to cover it?

2022-04-26 15:48 UTC, hugovk commented on README.md
> +  whether borders are still drawn within the table even when border = False.
```suggestion
  whether borders are still drawn within the table even when `border=False`.
```

2022-05-04 14:13 UTC, myheroyuki commented
Hi @hugovk, I made the changes you requested. If there are any other changes you'd like me make just let me know. Thanks!

2022-05-05 13:27 UTC, hugovk approved these changes

2022-05-05 13:27 UTC, hugovk commented
Thanks!

2022-05-05 13:27 UTC, merged