add markdown style
prettytable/prettytable pull request #19
Opened 2019-08-13 03:43 UTC by weakiwi

add markdown table style suppoty

2020-03-13 15:57 UTC, hugovk commented on prettytable.py
> +MARKDOWN = 28
Any particular reason for putting this at the end and choosing `28`, and not putting it after `PLAIN_COLUMNS`?

2020-03-13 15:57 UTC, hugovk commented on prettytable_test.py
> +from prettytable import (ALL, MSWORD_FRIENDLY, MARKDOWN, NONE, PrettyTable, from_csv,
It doesn't look like Markdown is actually being tested here?

2020-03-16 01:49 UTC, weakiwi commented on prettytable.py
> +MARKDOWN = 28
You are correct. Let me fix this

2020-03-16 02:09 UTC, weakiwi commented on prettytable_test.py
> +from prettytable import (ALL, MSWORD_FRIENDLY, MARKDOWN, NONE, PrettyTable, from_csv,
Let me add test case

2020-03-16 08:25 UTC, hugovk requested changes
A couple of little suggestions.

Also, to fix the [lint check on the CI](https://github.com/jazzband/prettytable/pull/19/checks?check_run_id=510020506), please run:

```sh
pip install -U black isort
black .
isort -y
```
Thanks!

2020-03-16 08:25 UTC, hugovk commented on README.md
> +  * `MARKDOWN` - A style that follows markdown syntax
```suggestion
  * `MARKDOWN` - A style that follows Markdown syntax
```

2020-03-16 08:25 UTC, hugovk commented on prettytable.py
> +            self._set_markdown_style()
Minor thing, let's also move this block before `RANDOM`

2020-03-16 08:25 UTC, hugovk commented on prettytable_test.py
> +        assert result.strip() == """| Field 1 | Field 2 | Field 3 |
Add a newline for readability and consistency with the others
```suggestion
        assert result.strip() == """
| Field 1 | Field 2 | Field 3 |
```

2020-03-16 08:25 UTC, hugovk commented on prettytable_test.py
> +| value 7 |  value8 |  value9 |""".strip()
```suggestion
| value 7 |  value8 |  value9 |
""".strip()
```

2020-03-16 14:04 UTC, hugovk commented on prettytable_test.py
> +            == """| Field 1 | Field 2 | Field 3 |
```suggestion
            == """
| Field 1 | Field 2 | Field 3 |
```

2020-03-17 13:29 UTC, weakiwi reviewed
all fix

2020-03-17 13:54 UTC, hugovk approved these changes

2020-03-17 13:54 UTC, merged

2020-03-17 13:54 UTC, hugovk commented
Thanks!