Bugfix colortable 290
prettytable/prettytable pull request #299
Opened 2024-04-19 01:42 UTC by av-guy

The issue that the `ColorTable` is experiencing deals with its incorporation of ANSI escape character sequences. The `ColorTable` class works by incorporating ANSI escape character sequences both before and after the character it represents. That creates a discrepancy in how `PrettyTable` and `ColorTable` portray the same character.

I altered how `_stringify_title` computes its width. Instead of relying on `self._hrule`, it now uses the padding widths and the widths of the columns themselves. From my testing, this seems to work well. I also modified the way `_stringify_header` slices the `bits` value. The old code used hard values of `1` and `-1`, which doesn't account for the length of a single character when someone uses `ColorTable`.

If you see anything that stands out, or you have input on a different solution, please let me know. I am open to the discussion. Also, I didn't see any tests related to the table rendering for `ColorTable`, so I didn't add any. All of the original tests are passing for both `ColorTable` and `PrettyTable` with these recent changes.

2024-04-19 06:23 UTC, hugovk requested changes
Thanks for the PR!

Please could you:

* Update the title to be more descriptive? It will be used in the release notes. See https://github.com/jazzband/prettytable/releases to get an idea.

* Add "Fixes #xxx" with the issue number to the PR description, so the issue will be closed when this is merged.

* Add tests. It's good none of the existing tests fail. It will be even better to add tests which fail with current `main` and pass with this PR, so we can avoid regressions in the future.

2024-04-19 06:23 UTC, hugovk commented on src/prettytable/prettytable.py
> +        bits.append(self._justify(title, sum(total_widths) - 1, "c"))
Creating and summing a tuple is nearly 2x as fast as a list:

```suggestion
        sum_widths = sum((n + lpad + rpad + 1 for n in self._widths))

        bits.append(self._justify(title, sum_widths - 1, "c"))
```

2024-04-20 20:47 UTC, av-guy commented
> Thanks for the PR!
> 
> Please could you:
> 
> * Update the title to be more descriptive? It will be used in the release notes. See https://github.com/jazzband/prettytable/releases to get an idea.
> * Add "Fixes #xxx" with the issue number to the PR description, so the issue will be closed when this is merged.
> * Add tests. It's good none of the existing tests fail. It will be even better to add tests which fail with current `main` and pass with this PR, so we can avoid regressions in the future.

I will try to get the tests done today. I did change the PR description. Does the new description satisfy the first two requirements in your list?

2024-04-20 20:50 UTC, hugovk commented
Looks good, except please move "Fixes #xxx" from the title to PR the description.

2024-04-20 21:05 UTC, av-guy commented
> Looks good, except please move "Fixes #xxx" from the title to PR the description.

I added Fixes #290 to my original comment. I don't contribute very often, so if I did this wrong, please let me know.

2024-04-20 22:42 UTC, av-guy commented
> Looks good, except please move "Fixes #xxx" from the title to PR the description.

I added a basic test for the color table. Please see the most commit df8f2e6 and provide any feedback as necessary.

2024-04-28 19:21 UTC, hugovk commented on src/prettytable/prettytable.py
> +        sum_widths = sum(n + lpad + rpad + 1 for n in self._widths)
Actually, my last suggestion was wrong, and summing a list comprehension is faster than a generator:

```console
❯ python -m timeit -s "a = (1,2,3,4,4,6,7,8,9)" "sum(tuple(n for n in a))"
1000000 loops, best of 5: 363 nsec per loop

❯ python -m timeit -s "a = (1,2,3,4,4,6,7,8,9)" "sum(n for n in a)"
1000000 loops, best of 5: 270 nsec per loop

❯ python -m timeit -s "a = (1,2,3,4,4,6,7,8,9)" "sum([n for n in a])"
2000000 loops, best of 5: 168 nsec per loop
```


```suggestion
        sum_widths = sum([n + lpad + rpad + 1 for n in self._widths])
```

2024-04-28 19:24 UTC, hugovk approved these changes
Thank you!

2024-04-28 19:29 UTC, merged